name: Build Flatpak
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      # Dependencies
      # --------------------------------------
      - name: Install build dependencies
        run: |
          sudo apt install -y flatpak-builder

      # Flatpak
      # --------------------------------------
      - name: Build flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --user  --force-clean --repo=repo --install-deps-from=flathub flatpak com.github.mirkobrombin.docui.yml
          flatpak build-bundle repo com.github.mirkobrombin.docui.flatpak com.github.mirkobrombin.docui --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: Continuous
          title: Continuous build
          files: |
            com.github.mirkobrombin.docui.flatpak
